version: "3.4"

services:

  consul_server:
    image: inoc/consul${TAG}
    labels: [app=consul]
    ports:
      - "8700:8700"
      - "8500:8500"
    networks:
      consul-net:
        aliases:
          - server.consul.swarm.container  
        
    environment:
        - 'CONSUL_LOCAL_CONFIG={"skip_leave_on_interrupt": true}'
     #   - CONSUL_BIND_CIDR=10.250.250.0/24
        - CONSUL=consul
        - CONSUL_CHECK_LEADER=true
   #     - CONSUL_BIND_ADDR="{{ GetPrivateInterfaces | include \"network\" \"10.250.250.0/24\" | unique \"name\" | attr \"address\" }}"
    command: "consul agent -server -bootstrap-expect=3 -ui -client=0.0.0.0 -retry-interval=5s -disable-host-node-id -config-file=/run/secrets/consul_server_config.json"    
    deploy:
      mode: replicated
      replicas: 3
      resources:
        reservations:
          memory: 128M
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 30s
        failure_action: pause

    secrets:
      - consul_server_config.json
      - consul_ca_file.cer
      - consul_cert_file.cer
      - consul_key_file.key

networks:
  consul-net:
    driver: overlay
    driver_opts:
      encrypted: ""
    ipam:
      driver: default
      config:
        - subnet: 10.250.250.0/24 # If changed, change the server config also.

secrets:
  consul_server_config.json:
    file: ./data/server_config.json
  consul_ca_file.cer:
    file: ./data/certificates/consul-root.cer
  consul_cert_file.cer:
    file: ./data/certificates/server.docker_dc1.consul.crt
  consul_key_file.key:
    file: ./data/certificates/server.docker_dc1.consul.key

